name: Development Auto Deploy

on:
  push:
    branches:
      - dev

  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Connect Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Deploy Development Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}

          script: |
            set -e

            cd /opt/pitjarus-backend

            git fetch origin

            git reset --hard origin/dev

            docker compose -f docker-compose.dev.yml up -d --build

            sleep 10
